# Optionally set the version of Python and requirements required to build your docs

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats: all

python:
  install:
    - requirements: rtd-requirements.txt

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - gcc
    - libstdc++6
  jobs:
    post_install:
      - git clone --recursive https://github.com/tmolteno/python-necpp/
      - cd python-necpp/PyNEC && bash build.sh
      - python python-necpp/PyNEC/setup.py install